development:
  stripe_secret_key: 'sk_test_51J4gjNSASr6Z8gvjIkvF4tfN6PALZfcbYH33yJM6wjy6CbwyGWdpobGk1cHlEHTg4j1Cty68Ky0UjzajrgLTmaoK003Dwrncd1'
  stripe_publishable_key: 'pk_test_51J4gjNSASr6Z8gvjsGSeHnHZTPZvN3XBYu30FBwnBYb9FQH0z331LYwSn8Sw2NyDSLeUBQkK8gpcsjPNeeYcOPE100qVbJCNdr'